"""empty message

Revision ID: 139bb60beb70
Revises: c4879bf70f15
Create Date: 2023-04-14 12:54:39.722289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139bb60beb70'
down_revision = 'c4879bf70f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conta', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conta', type_='foreignkey')
    op.drop_column('conta', 'usuario_id')
    # ### end Alembic commands ###
