"""empty message

Revision ID: 486897bdf04a
Revises: 340038c62841
Create Date: 2023-04-10 13:52:49.031114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486897bdf04a'
down_revision = '340038c62841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('resumo', sa.String(length=150), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operacao')
    # ### end Alembic commands ###
